### ISSUE TITLE
Issue with Azure OIDC: "Identity not found"

### ISSUE THREAD

**Issue by jooooel** [pulumi/actions#1045] opened 2023-12-08 15:33 UTC
### What happened?

I'm trying to run `pulumi preview` in a GitHub Action using federated credentials with Azure OIDC. The federated credentials seem to be correctly setup. After logging in to Azure, I can access the key vault key that is used for encryption.

However, when running the Pulumi action, I get the following error:

```
Run pulumi/actions@v4
  with:
    pulumi-version: 3.96.1
    command: preview
    stack-name: tst
    cloud-url: azblob://<container>?storage_account=<storage-account>
    comment-on-pr: true
    diff: true
    work-dir: ***
    comment-on-summary: false
    github-token: ***
    expect-no-changes: false
    target-dependents: false
    refresh: false
    upsert: false
    remove: false
    edit-pr-comment: true
    color: auto
    exclude-protected: false
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    ARM_USE_OIDC: true
  
Configured range: 3.96.1
/usr/local/bin/pulumi version
v3.95.0
warning: A new version of Pulumi is available. To upgrade from version '3.95.0' to '3.96.1', visit https://pulumi.com/docs/install/ for manual instructions and release notes.
Pulumi 3.95.0 does not satisfy the desired version 3.96.1. Proceeding to download
Matched version: v3.96.1
Install destination is /home/runner/.pulumi
Successfully deleted pre-existing /home/runner/.pulumi/bin
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/.pulumi -f /home/runner/work/_temp/76343dcc-b529-48ab-8c76-d3b347de74fa
Logging into azblob://<container>?storage_account=<storage-account>
pulumi preview on tst
  
  /home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77
                      : new CommandError(result);
  ^
  CommandError: code: -2
   stdout: 
   stderr: Command failed with exit code 255: pulumi preview --diff --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --event-log /tmp/automation-logs-preview-MrmOCd/eventlog.txt --stack tst --non-interactive
  warning: GOCOVERDIR not set, no coverage data emitted
  error: getting stack configuration: get stack secrets manager: secrets (code=InvalidArgument): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://***.vault.azure.net/keys/pulumi-encryption-key-tst/***/decrypt?api-version=7.0: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
   err?: Error: Command failed with exit code 255: pulumi preview --diff --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --event-log /tmp/automation-logs-preview-MrmOCd/eventlog.txt --stack tst --non-interactive
  warning: GOCOVERDIR not set, no coverage data emitted
  error: getting stack configuration: get stack secrets manager: secrets (code=InvalidArgument): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://***.vault.azure.net/keys/pulumi-encryption-key-tst/***/decrypt?api-version=7.0: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
  
      at Object.createCommandError (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77:1)
      at Object.<anonymous> (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:76:1)
      at Generator.throw (<anonymous>)
      at rejected (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:19:1)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Example

This is what I have in my GitHub Action

```
  - name: "Login via Az module"
	uses: azure/login@v1
	with:
	  client-id: ${{ secrets.azure_client_id }}
	  tenant-id: ${{ secrets.azure_tenant_id }}
	  subscription-id: ${{ secrets.azure_subscription_id }}

  - name: Test Federated Credentials Login
	shell: bash
	run: |
	  az keyvault key show --vault-name *** --name pulumi-encryption-key-tst

  - name: "Pulumi preview"
	uses: pulumi/actions@v4
	with:
	  pulumi-version: 3.96.1
	  command: preview
	  stack-name: ${{ inputs.stack_name }}
	  cloud-url: ${{ inputs.stack_url }}
	  comment-on-pr: true
	  diff: true
	  work-dir: ${{ inputs.working_directory }}
	env:
	  ARM_USE_OIDC: "true"
```

### Output of `pulumi about`

Not relevant in this case? Running in GitHub Action

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2023-12-09 08:17
It looks like this may be related to a bug in Pulumi v3.96.1 (https://github.com/pulumi/pulumi/issues/14799) which was fixed in v3.96.2. Does it work if you set `pulumi-version: 3.96.2`?

**Comment by jooooel** [comment] 2023-12-09 08:55
I will try, but I think I’ve tried with older versions than 3.95 as well 🤔

**Comment by jooooel** [comment] 2023-12-09 09:08
Hm no. Same error unfortunately (without the GOCOVERDIR warning).

I’m not sure what the easiest way to debug this issue is, do you have any advice?

**Comment by tgummerer** [comment] 2024-01-09 22:58
@jooooel Sorry about the delay.  I had a look at this issue now.  I believe the problem here is that the application that's used here doesn't have the decrypt permission set up in Azure. Following [this guide](https://learn.microsoft.com/en-us/azure/key-vault/general/assign-access-policy?tabs=azure-portal) the identity that's being used needs at least Get and Decrypt permissions so the CI example above succeeds.  

With pulumi 3.101.0, which we're in the process of releasing now there's gonna be a better error message for this as well (through our updating of `gocloud.dev`), and will look something like this, which I think will help debugging similar issues in the future:

```
  error: getting stack configuration: get stack secrets manager: secrets (code=PermissionDenied): POST [redacted]
  --------------------------------------------------------------------------------
  RESPONSE 403: 403 Forbidden
  ERROR CODE: Forbidden
  --------------------------------------------------------------------------------
  {
    "error": {
      "code": "Forbidden",
      "message": "The user, group or application 'appid=***;oid=[...];iss=https://sts.windows.net/***/' does not have keys decrypt permission on key vault '[redacted];location=westus'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287",
      "innererror": {
        "code": "ForbiddenByPolicy"
      }
    }
  }
```

**Comment by tgummerer** [comment] 2024-01-09 23:00
If you want to try to get a better error message now you can try to install the dev version of the CLI using `pulumi-version: dev` as an argument to the pulumi action as well.

**Comment by tgummerer** [comment] 2024-01-11 18:06
Since I believe there's nothing we should do here and this works as designed I'm gonna close the issue out.  Feel free to reopen if you run into any other issues.

**Closed by tgummerer** 2024-01-11 18:06 UTC
Labels: kind/bug, resolution/by-design, awaiting-feedback
