### ISSUE TITLE
Action is not respecting `working-directory` config

### ISSUE THREAD

**Issue by rhuanbarreto** [pulumi/actions#890] opened 2023-03-22 09:24 UTC
### What happened?

The recommended way in github actions to define a working directory for an action is to use the         [`working-directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun) parameter. This is very useful in a case my whole infra is declared at a specific folder in a repo, like `./infra`.

If I use this parameter in my workflow, the action still tries to run at the root folder in the repo.

### Expected Behavior

It's expected from the action to use this directory instead of relying only on the `work-dir` parameter.

### Steps to reproduce

Some fields were redacted.

```yaml
name: Pulumi
on:
  pull_request:
    branches:
      - main

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
          cache: pip
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Preview Infra Changes
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: ${{org}}/${{project}}/${{ matrix.environment }}
          comment-on-pr: true
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.APP_TENANT_ID }}

```

### Output of `pulumi about`

```
CLI          
Version      3.58.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.97.0
azuread       5.36.0
python        unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in python: executable='<redacted>/.pyenv/shims/python3' version='3.11.2
'

Current Stack: <redacted>

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/<redacted>
User           <redacted>
Organizations  <redacted>

Dependencies:
NAME                 VERSION
pip                  23.0.1
pulumi-azure-native  1.97.0
pulumi-azuread       5.36.0
setuptools           67.4.0
wheel                0.38.4
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment] 2023-03-22 18:17
Hey there @rhuanbarreto! I can definitely understand this use case.

However, I believe the `working-directory` option only modifies `run` steps. Steps that employ `uses` (_i.e._ steps that don't run as shell commands but execute other Actions) aren't modified by the `working-directory` option. I think the GHA syntax documentation explains this distinction (albeit confusingly!). Note that `run` and `uses` are mutually exclusive. Looking through the syntax document, the `working-directory` option is referenced until `steps[*].run` and again in `default.run`. Here's a clip from [the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun):

> You can use defaults.run to provide default shell and working-directory options for all [run](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun) steps in a workflow.

From what I can tell, the GHA runtime doesn't apply `working-directory` before invoking the action when `uses` is employed. [This action] (https://github.com/pulumi/actions/blob/master/src/config.ts#L80) uses `./` when `work-dir` isn't set.

If I'm reading the docs correctly, I think this action is behaving as intended.

**Comment by rhuanbarreto** [comment] 2023-03-23 07:43
Thanks for the clarification! Then maybe changing to `working-directory` will harmonize with the naming from github? Or maybe this can generate confusion?

**Comment by RobbieMcKinstry** [comment] 2023-03-23 15:34
Sure thing! Always happy to help!
You might be right that `working-directory` is a better name! However, changing the name of the option would be a breaking change, so I don't think we'll likely make the change soon. :\ Sorry!

**Comment by RobbieMcKinstry** [comment] 2023-03-23 15:36
Happy to continue the discussion of course! I'm going to close this issue since it sounds like we agree it's not a bug in the code. :)

**Closed by RobbieMcKinstry** 2023-03-23 15:36 UTC
Labels: kind/bug, resolution/by-design, awaiting-feedback, area/cicd
